<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Dashboard <small>Statistics </small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Users
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

            <form role="form">
                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Name</label>
                        <input class="form-control" type="text" placeholder="Search with Name">

                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Email</label>
                        <input class="form-control" type="text" placeholder="Search with Email">

                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Mobile</label>
                        <input class="form-control" type="text" placeholder="Search with Mobile">

                    </div>
                </div>
                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Status</label>
                        <select class="form-control">
                            <option>Select</option>
                            <option>Active</option>
                            <option>Inactive</option>
                            <option>Pending</option>

                        </select>

                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Date</label>
                        <input class="form-control" type="text" placeholder="Search with Date">

                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Date From</label>
                        <input class="form-control" type="text" placeholder="Search between dates">

                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Date To</label>
                        <input class="form-control" type="text" placeholder="Search between dates">

                    </div>
                </div>


                <div class="col-lg-3">

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Search&nbsp;&nbsp;&nbsp;&nbsp;</button>

                    </div>
                </div>

            </form>


    </div>



</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> User Search Results </h3>
            </div>


                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Register/Update Date </th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="active">
                            <td>Atul Walkar</td>
                            <td>shrawan.walkar@gmail.com</td>
                            <td>99225515752 9595674545</td>
                            <td>29/07/2016 <br>30/07/2016</td>
                            <td>Active</td>
                        </tr>

                        </tbody>
                    </table>



        </div>
    </div>
</div>
<!-- /.row -->

