<?php

?>

<div id="content" style="min-height: 304px;">
    <div id="title">
        <h1 class="inner title-2">My Cart
            <ul class="breadcrumb-inner">
                <li> <a href="<?$this->basepath()?>">Home</a></li>
                <li> <a href="<?php $this->url('cart')?>">Cart</a></li>

            </ul>
        </h1>
    </div>
    <div class="inner">
<?php
//print_r($page);
//  var_dump($service);


?>

        <div class="content-inner">

            <!-- Content Center -->
            <div class="content-center candidate-list">
                <div class="box-1 search-bar-half" id="search-and-sort">

                </div>

                <div class="clear"></div>
                <div class="heading-l">
                    <h2> Available Jobs </h2>
                </div>





                <div class="clearfix"></div>
               
            </div>
            <!-- /Content Center -->

            <!-- Content Right -->
            <div class="content-right">
                <div class="block background" id="social-like">
                    <h2 class="title-1">Share Us With Your Friends</h2>
                    <div class="block-content">
                        <div class="social-like linkedin"><a href="#" class="like-button">LinkedIn</a><span class="count">500</span></div>
                        <div class="social-like motibu"><a href="#" class="like-button">Motibu</a><span class="count">2.7K</span></div>
                        <div class="social-like facebook"><a href="#" class="like-button">Facebook</a><span class="count">1.3K</span></div>
                        <div class="social-like twitter"><a href="#" class="like-button">Twitter</a><span class="count">868</span></div>
                    </div>
                </div>
                <div class="block border" id="advertising">
                    <div class="block-content"> <img alt="sidebarad" src="images/sb-ad.jpg">
                        <!-- <div class="advertising-test">300x250<br/>
                          Ad Banner</div>-->
                    </div>
                </div>


            </div>
            <!-- /Content Right -->

            <div class="clear"></div>

            <!-- Clear Line -->

        </div>


    </div>
</div>