<?php

?>

<div id="content" style="min-height: 304px;">
    <div id="title">
        <h1 class="inner title-2"><?php echo $serviceDet['serviceTitle'];?>
            <ul class="breadcrumb-inner">
                <li> <a href="<?$this->basepath()?>">Home</a></li>
                <li> <a href="<?php $this->url('cart')?>">Cart</a></li>

            </ul>
        </h1>
    </div>
    <div class="inner">
<?php
//print_r($page);
//  var_dump($service);


?>

        <div class="content-inner">

            <!-- Content Center -->
            <div class="content-center candidate-list">
                <div class="box-1 search-bar-half" id="search-and-sort">
                    <div id="search-partner">
                        <form action="http://uouapps.com/careers/post" id="search-partner-form">
                            <input type="text" class="textfield-with-callback combosexed" placeholder="Location" style="display: none;"><span class="combosex_main textfield combosex_with_append combosex_text"><span class="combosex_input_span"><span style="display: inline;" class="combosex_ph">Location</span><input type="text" value="" class="combosex_input combosex_input_3" autocomplete="off"><a class="combosex_append" rel="3">+</a></span><input type="hidden" class="combosex_def" value=""><input type="hidden" class="combosex_value" value=""><span class="combosex_spinner"></span></span>
                            <input type="text" class="textfield-with-callback combosexed" placeholder="Industry / Role" style="display: none;"><span class="combosex_main textfield combosex_with_append combosex_text"><span class="combosex_input_span"><span style="display: inline;" class="combosex_ph">Industry / Role</span><input type="text" value="" class="combosex_input combosex_input_4" autocomplete="off"><a class="combosex_append" rel="4">+</a></span><input type="hidden" class="combosex_def" value=""><input type="hidden" class="combosex_value" value=""><span class="combosex_spinner"></span></span>
                            <input type="submit" value="Search" class="pull-right" id="search-submit">
                        </form>
                    </div>
                </div>

                <div class="clear"></div>
                <div class="heading-l">
                    <h2> Available Jobs </h2>
                </div>

                <div class="job-page-top-nav-bar">

                    <div class="job-page-sorter">
                        <div class="sorter-select">
                            <select class="select combosexed" style="display: ;">
                                <option selected="selected" value="Sort By">- Sort By -</option>
                                <option value="Sort Criterion 1">Sort Criterion 1</option>
                                <option value="Sort Criterion 2">Sort Criterion 2</option>
                                <option value="Sort Criterion 3">Sort Criterion 3</option>
                            </select><span class="combosex_main select combosex_with_append combosex_select"><span class="combosex_arrow combosex_arrow_down" style="width: 14px;"><em></em></span><span class="combosex_input_span"><a class="combosex_display" href="javascript:void(0)">- Sort By -</a></span><input type="hidden" class="combosex_def" value="Sort By"><input type="hidden" class="combosex_value" value="Sort By"><span class="combosex_spinner"></span></span>
                        </div>
                    </div>
                    <div class="search-count">451 Results Found</div>
                    <div class="pager">
                        <ul>
                            <li class="prev noactive"><a></a></li>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">6</a></li>
                            <li class="next"><a href="#"></a></li>
                        </ul>
                    </div>

                </div>

                <div id="job-content-fields">

                    <div class="view_mode" id="cells">
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="field-container odd box-1 hide">
                            <div class="nav-buttons">
                                <ul>
                                    <li class="show-hide hide"><a></a></li>
                                    <li class="favorite"><a href="#"></a></li>
                                    <li class="link"><a href="job.html"></a></li>
                                </ul>
                            </div>
                            <div class="cells-job-thumb"> <img alt="Thumb" src="images/recruiter.jpg"> </div>
                            <div class="header-fields">
                                <div class="title-company">
                                    <div class="title"><a href="job.html">Abu Antar</a></div>
                                    <div class="company">24 Years Old - Sydney, AU</div>
                                </div>
                                <ul class="social_media_icons job">
                                    <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
                                    <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
                                </ul>
                            </div>
                            <div class="body-field">
                                <div class="teaser">
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit.<span class="read-more"><a>Read More</a></span></p>
                                </div>
                                <div class="full-body" style="display: none;">
                                    <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                                </div>
                                <ul class="candidate-meta meta-fields">
                                    <li class="pull-left">Experience: <span>5 Years</span></li>
                                    <li class="pull-center">Degree: <span>MBA</span></li>
                                    <li class="pull-right">Career Level: <span>Mid Career</span></li>
                                </ul>
                                <div class="block-fields" style="display: none;">
                                    <div class="block skills">
                                        <h4>Required Skills</h4>
                                        <div class="block-content">
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">5 Years of Experience</div>
                                                    <div class="progressbar"><span data-level="60" class="progress-count" style="width: 60%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description hide">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">Perfect Written &amp; Spoken English</div>
                                                    <div class="progressbar"><span data-level="100" class="progress-count" style="width: 100%;"></span></div>
                                                    <div class="description" style="display: none;">...</div>
                                                </div>
                                            </div>
                                            <div class="field roll-with-description show">
                                                <div class="roll-button"><span></span></div>
                                                <div class="roll-field">
                                                    <div class="label">3 Foreign Languages</div>
                                                    <div class="progressbar"><span data-level="65" class="progress-count" style="width: 65%;"></span></div>
                                                    <div class="description" style="display: block;">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                                                </div>
                                            </div>
                                            <!-- Cleaner -->
                                            <div class="clear"></div>
                                            <!-- /Cleaner -->
                                        </div>
                                    </div>
                                    <div class="block">
                                        <h4>Additional Requirements</h4>
                                        <div class="block-content">
                                            <div class="tag-field">Work Permit</div>
                                            <div class="tag-field">5 Years Experience</div>
                                            <div class="tag-field">MBA</div>
                                            <div class="tag-field">Magento Certified</div>
                                            <div class="tag-field">Perfect Written &amp; Spoken English</div>
                                        </div>
                                        <!-- Cleaner -->
                                        <div class="clear"></div>
                                        <!-- /Cleaner -->
                                    </div>
                                </div>
                                <div class="buttons-field applybtns" style="display: none;">
                                    <div class="apply"><a href="#">Contact Me</a></div>
                                    <div class="full"><a href="#">Contact On MotibU</a></div>
                                </div>
                            </div>
                        </div>

                    </div>

                </div>

                <div class="clearfix"></div>
                <div class="job-page-top-nav-bar">

                    <div class="job-page-sorter">
                        <div class="sorter-select">
                            <select class="select combosexed" style="display: none;">
                                <option selected="selected" value="Sort By">- Sort By -</option>
                                <option value="Sort Criterion 1">Sort Criterion 1</option>
                                <option value="Sort Criterion 2">Sort Criterion 2</option>
                                <option value="Sort Criterion 3">Sort Criterion 3</option>
                            </select><span class="combosex_main select combosex_with_append combosex_select"><span class="combosex_arrow combosex_arrow_down" style="width: 14px;"><em></em></span><span class="combosex_input_span"><a class="combosex_display" href="javascript:void(0)">- Sort By -</a></span><input type="hidden" class="combosex_def" value="Sort By"><input type="hidden" class="combosex_value" value="Sort By"><span class="combosex_spinner"></span></span>
                        </div>
                    </div>

                    <div class="pager">
                        <ul>
                            <li class="prev noactive"><a></a></li>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">6</a></li>
                            <li class="next"><a href="#"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
            <!-- /Content Center -->

            <!-- Content Right -->
            <div class="content-right">
                <div class="block background" id="social-like">
                    <h2 class="title-1">Share Us With Your Friends</h2>
                    <div class="block-content">
                        <div class="social-like linkedin"><a href="#" class="like-button">LinkedIn</a><span class="count">500</span></div>
                        <div class="social-like motibu"><a href="#" class="like-button">Motibu</a><span class="count">2.7K</span></div>
                        <div class="social-like facebook"><a href="#" class="like-button">Facebook</a><span class="count">1.3K</span></div>
                        <div class="social-like twitter"><a href="#" class="like-button">Twitter</a><span class="count">868</span></div>
                    </div>
                </div>
                <div class="block border" id="advertising">
                    <div class="block-content"> <img alt="sidebarad" src="images/sb-ad.jpg">
                        <!-- <div class="advertising-test">300x250<br/>
                          Ad Banner</div>-->
                    </div>
                </div>


            </div>
            <!-- /Content Right -->

            <div class="clear"></div>

            <!-- Clear Line -->

        </div>


    </div>
</div>