<?php

?>

<div id="content" style="min-height: 304px;">
    <div id="title">
        <h1 class="inner title-2">My Cart
            <ul class="breadcrumb-inner">
                <li> <a href="<?$this->basepath()?>">Home</a></li>
                <li> <a href="<?php $this->url('cart')?>">Cart</a></li>

            </ul>
        </h1>
    </div>
    <div class="inner">
<?php
//print_r($page);
//  var_dump($service);


?>


        <div class="content-inner">

            <!-- Content Center -->
            <div class="content-center candidate-list">


                <div class="clear"></div>
                <div class="heading-l">
                    <h2> My Cart Details </h2>
                </div>

                <div class="box-1" >

                    <table class="table table-condensed cartTable" id="cartTable">
                        <tr class="cartTableRow"><td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF">  <span style="margin-left: 1em;"> Service Details  </span></td> <td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF"> Price  </td></td><td style="background-color: #4D4D4D; font: 900; color: #FFF" class="cartTableCell">&nbsp;</td></tr>



                        <?php


                        $totalAmount = 0;
                        foreach($cartDetails  as $cart){
                            $brackets = "";
                            if($cart['optionTitle'] !="" || $cart['optionTitle'] !="&nbsp;" ){
                                $brackets = "( ".$cart['optionTitle'] . " )";

                            }

                            ?>

                            <tr class="cartTableRow"><td class="cartTableCell">  <span style="margin-left: 1em;"><?php echo $cart['serviceTitle']." ".$brackets ?> </span></td> <td class="cartTableCell"> <?php echo $cart['price'] ?> </td></td><td class="cartTableCell">
                                    <span style="color: red"><a href="#" data-optiondata ="<?php echo $cart['serviceOptionId'] ?>-#-<?php echo $cart['optionTitle'] ?>-#-<?php echo $cart['serviceId'] ?>" onclick="removePackage(this)" data-price='<?php echo $cart['price'] ?>' >X

                                        </a></span></td></tr>


                            <?php
                            $totalAmount = $totalAmount + $cart['price'];

                        }

                        ?>


                    </table>

                </div>



                <div class="clearfix"></div>
                <form method="post" action="<?php echo $this->url("cart",array("action"=>"process"))?>">

                <div class="box-1" >

                    <table class="table table-condensed cartTable">

                        <tr class="cartTableRow"  style="display:none"><td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF;">
                                <span style="margin-left: 1em">Select Gateway</span> </td>
                            <td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF;">
                                <select class="form-control" name="gateway">
                                    <option value="razorpay">RazorPay</option>
                                    <option value="paytm" selected="selected">PayTM</option>

                                </select>
                            </td>
                        </tr>

                        <tr class="cartTableRow"><td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF">
                                <span style="margin-left: 1em"> <button class="btn btn-success" type="submit" id="proceed">Proceed to checkout</button> </span> </td>
                            <td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF;">
                                <input type="hidden" name="amount" value="<?php echo $totalAmount;?>" id="totalAmountForm" >
                                <span style="margin-left: -1em;" id="totalAmount"><?php echo $totalAmount;?></span>
                            </td>
                        </tr>


                    </table>


                </div>
                </form>


                <div class="clearfix"></div>



            </div>
            <!-- /Content Center -->

            <!-- Content Right -->
            <div class="content-right"  style="margin-top: 4.1em;">

                <div class="block border" >
                    <div class="block-content">
                        <table class="table table-condensed cartTable">
                            <tr class="cartTableRow"><td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF">
                                    <span style="margin-left: 1em">More Services </span> </td>
                                <td class="cartTableCell" style="background-color: #4D4D4D; font: 900; color: #FFF;">
                                    <span style="margin-left: -1em;"></span> </td></td></tr>

                            <?php
                            foreach($serviceOptions as $serviceOption => $so1 ){
                            ?>
                            <tr class="serviceHeading">
                                    <td style="background-color: #4D4D4D; font: 900; color: #FFF;">
                                        <?php echo $serviceOption?>
                                        </td>
                                </tr>


                            <?php
                                foreach($so1 as $service){

                                    ?>
                                    <tr>
                                    <td>


                                        <table>
                                            <tr >
                                                <td style="width: 20%;">

                                                 <span>  <input style="display: block !important; float: left" type="checkbox"
                                                       name="price" data-optiondata="<?php echo $service['serviceOptionId'] ?>-#-<?php echo $service['optionTitle'] ?>-#-<?php echo $service['serviceId'] ?>-#-<?php echo $serviceOption ?>"
                                                       value="<?php echo $service['price'] ?>" onchange="addtoCart(this);"> </span>

                                                </td>
                                                <td style="width: 80%">
                                                    <span style="margin-left: 0.5em;"><?php echo $service['optionTitle']?><br/>  </span>
                                                </td>
                                            </tr>

                                        </table>
                                    </td>
                                    </tr>

                             <?php

                                }
                            ?>



                            </td>
                            </tr>
                            <?php

                            }

                         /*   $brackets = "";
                            foreach($services as $service){
                                $brackets = "";
                                if($service['optionTitle'] !="" || $service['optionTitle'] !="&nbsp;" ){
                                    $brackets = "( ".$service['optionTitle'] . " )";

                                }
                                ?>
                                <tr class="cartTableRow">
                                    <td class="cartTableCell">
                                        <span style="margin-left: 1em;"> <?php echo $service['serviceTitle']."<br>".$brackets?></span>
                                        <span>  <input style="display: block !important; float: left" type="radio"
                                                       name="price" data-optiondata="<?php echo $service['serviceOptionId'] ?>-#-<?php echo $service['serviceOptionTitle'] ?>"
                                                       value="<?php echo $service['price'] ?>"></span>


                                    </td>
                                </tr>
                                <?php
                            }
                         */
                            ?>


                        </table>

                    </div>
                </div>


            </div>
            <!-- /Content Right -->

            <div class="clear"></div>

            <!-- Clear Line -->

        </div>


    </div>
</div>
<style>
    .cartTable{
        padding: 0.2em;

    }
    .cartTableRow{
        height: 4em;

    }
    .cartTableCell{
        padding: 1em;
        vertical-align:middle !important;

    }


</style>
<script>
    window.totalAmount= <?php echo $totalAmount;?>
</script>