
<div id="content" style="min-height: 81px;">
    <div id="title">
        <h1 class="inner title-2">Contact Us
            <ul class="breadcrumb-inner">
                <li> <a href="index.html">Home</a></li>
                <li> <a href="contacts.html">Contact Us</a></li>
            </ul>
        </h1>
    </div>
    <div class="inner">



            <!-- Content Right -->
            <div class="content formWrapper beautyforms">
                <div class="block background " style="background-image:url(' <?php echo $this->basepath('css/dark_wall.png') ?>');">
                   <!-- <h1 class="">Sign Up</h1> -->
                   <br>




                    <form class="form" method="post" action="yourpage.html">
                        <input type="text" class="name" placeholder="Name">
                        <div>
                            <p class="name-help">Please enter your first and last name.</p>
                        </div>
                        <input type="email" class="email" placeholder="Email">
                        <div>
                            <p class="email-help">Please enter your current email address.</p>
                        </div>
                        <input type="submit" class="submit" value="Register">
                    </form>



                    <div class="block-content beautyforms">
                        <form id="contact" class="form-horizontal well" method="post" action="#">
                            <p>Sign up for a great Stint  </p>
                            <div id="about">
                                <input type="text" placeholder="Name" class="textfield combosexed" name="name" title="Your Name" style="display: none;"><span class="combosex_main textfield combosex_with_append combosex_text"><span class="combosex_input_span"><span style="display: inline;" class="combosex_ph">Name</span><input type="text" value="" class="combosex_input combosex_input_1" autocomplete="off"><a class="combosex_append" rel="1">+</a></span><input type="hidden" class="combosex_def" value=""><input type="hidden" class="combosex_value" value=""><span class="combosex_spinner"></span></span>
                                <input type="text" placeholder="E-mail" class="textfield combosexed" name="email" title="Your E-Mail" style="display: none;"><span class="combosex_main textfield combosex_with_append combosex_text"><span class="combosex_input_span"><span style="display: inline;" class="combosex_ph">E-mail</span><input type="text" value="" class="combosex_input combosex_input_2" autocomplete="off"><a class="combosex_append" rel="2">+</a></span><input type="hidden" class="combosex_def" value=""><input type="hidden" class="combosex_value" value=""><span class="combosex_spinner"></span></span>
                                <input type="text" placeholder="WebSite" class="textfield combosexed" name="website" title="Your WebSite" style="display: none;"><span class="combosex_main textfield combosex_with_append combosex_text"><span class="combosex_input_span"><span style="display: inline;" class="combosex_ph">WebSite</span><input type="text" value="" class="combosex_input combosex_input_3" autocomplete="off"><a class="combosex_append" rel="3">+</a></span><input type="hidden" class="combosex_def" value=""><input type="hidden" class="combosex_value" value=""><span class="combosex_spinner"></span></span>
                            </div>
                            <div id="mess">
                                <textarea onblur="$(this).removeClass('active');" onfocus="$(this).addClass('active');" onclick="this.value='';" class="textarea" rows="6" cols="30" name="message" title="Your Message">How can I help you?</textarea>
                            </div>
                            <div id="send">
                                <button class="btn blue">Send Message</button>
                            </div>
                        </form>




                        <form id="regform" class="form-horizontal well" method="post" action="#">
                            <fieldset>
                                <legend>Register</legend>
                                <div class="control-group">
                                    <label for="input01" class="control-label">Email </label>
                                    <div class="controls">
                                        <input type="text" id="email" class="input-xlarge" name="email" >
                                        <p class="help-block error" id="emailError" > </p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="input01" class="control-label">Password </label>
                                    <div class="controls">
                                        <input type="password" id="passwd" class="input-xlarge" name="passwd" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="input01" class="control-label">Confirm Password </label>
                                    <div class="controls">
                                        <input type="password" id="cpasswd" class="input-xlarge" name="cpasswd" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>


                                <div class="control-group">
                                    <label for="input01" class="control-label">First Name</label>
                                    <div class="controls">
                                        <input type="text" id="fname" class="input-xlarge" name="firstName" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="input01" class="control-label">Last Name</label>
                                    <div class="controls">
                                        <input type="text" id="lname" class="input-xlarge" name="lastName" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>


                                <div class="control-group">
                                    <label for="input01" class="control-label">Mobile</label>
                                    <div class="controls">
                                        <input type="text" id="mobile" class="input-xlarge" name="mobile" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="input01" class="control-label">City</label>
                                    <div class="controls">
                                        <input type="text" id="city" class="input-xlarge" name="city" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="input01" class="control-label">State</label>
                                    <div class="controls">
                                        <input type="text" id="state" class="input-xlarge" name="state" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="input01" class="control-label">Country</label>
                                    <div class="controls">
                                        <input type="text" id="country" class="input-xlarge" name="country" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="input01" class="control-label">Zip</label>
                                    <div class="controls">
                                        <input type="text" id="zip" class="input-xlarge" name="zip" >
                                        <p class="help-block error" > </p>
                                    </div>
                                </div>


                                <div class="control-group">
                                    <label for="input01" class="control-label">&nbsp;</label>

                                </div>


                                <div class="form-actions">
                                    <button class="btn btn-primary" type="submit">Save changes</button>
                                    <!--<button class="btn" type="reset">Cancel</button> -->
                                </div>

                                <div class="control-group">
                                    <div style="font-size: 19px; color: #1e689a; height: 40px; margin-top:20px; display: none;  " id="regMsgs">
                                        <img src = "<?php echo  $this->basepath("images/loader.gif");?>"> <span>Please wait while we register you </span>
                                    </div>

                                </div>

                            </fieldset>
                        </form>



                    </div>
                </div>
            </div>
            <!-- /Content Right -->

            <div class="clear"></div>
            <!-- Clear Line -->

        </div>
        <!-- /Content Inner -->

    </div>
</div>