<div class="row" >


    <div class="col-md-12 min-height-400">
        <h3 class="bottom-margin-5"></h3><br>


            <div class="span7 offset1">


                <form id="regform" class="form-horizontal well" method="post" action="#">
                    <fieldset>
                        <legend>Register</legend>
                        <div class="control-group">
                            <label for="input01" class="control-label">Email </label>
                            <div class="controls">
                                <input type="text" id="email" class="input-xlarge" name="email" >
                                <p class="help-block error" id="emailError" > </p>
                            </div>
                        </div>

                        <div class="control-group">
                            <label for="input01" class="control-label">Password </label>
                            <div class="controls">
                                <input type="password" id="passwd" class="input-xlarge" name="passwd" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>

                        <div class="control-group">
                            <label for="input01" class="control-label">Confirm Password </label>
                            <div class="controls">
                                <input type="password" id="cpasswd" class="input-xlarge" name="cpasswd" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>


                        <div class="control-group">
                            <label for="input01" class="control-label">First Name</label>
                            <div class="controls">
                                <input type="text" id="fname" class="input-xlarge" name="firstName" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>

                        <div class="control-group">
                            <label for="input01" class="control-label">Last Name</label>
                            <div class="controls">
                                <input type="text" id="lname" class="input-xlarge" name="lastName" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>


                        <div class="control-group">
                            <label for="input01" class="control-label">Mobile</label>
                            <div class="controls">
                                <input type="text" id="mobile" class="input-xlarge" name="mobile" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>

                        <div class="control-group">
                            <label for="input01" class="control-label">City</label>
                            <div class="controls">
                                <input type="text" id="city" class="input-xlarge" name="city" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>

                        <div class="control-group">
                            <label for="input01" class="control-label">State</label>
                            <div class="controls">
                                <input type="text" id="state" class="input-xlarge" name="state" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>

                        <div class="control-group">
                            <label for="input01" class="control-label">Country</label>
                            <div class="controls">
                                <input type="text" id="country" class="input-xlarge" name="country" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>

                        <div class="control-group">
                            <label for="input01" class="control-label">Zip</label>
                            <div class="controls">
                                <input type="text" id="zip" class="input-xlarge" name="zip" >
                                <p class="help-block error" > </p>
                            </div>
                        </div>


                        <div class="control-group">
                            <label for="input01" class="control-label">&nbsp;</label>

                        </div>


                        <div class="form-actions">
                            <button class="btn btn-primary" type="submit">Save changes</button>
                            <!--<button class="btn" type="reset">Cancel</button> -->
                        </div>

                        <div class="control-group">
                            <div style="font-size: 19px; color: #1e689a; height: 40px; margin-top:20px; display: none;  " id="regMsgs">
                                <img src = "<?php echo  $this->basepath("images/loader.gif");?>"> <span>Please wait while we register you </span>
                            </div>

                        </div>

                    </fieldset>
                </form>
            </div>



    </div>




</div>