<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Dashboard <small>Statistics </small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Payment Status
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

        <form role="form" method="post" id="confirmPaymentForm" action="<?php echo $this->url("payment",array("action"=>"confirm"))?>">

            <div class="col-lg-3">

                <div class="form-group">
                    <label>Email</label>
                    <input class="form-control" type="text" placeholder="Search with Email" id="email" name="email">

                </div>
            </div>

            <div class="col-lg-3">

                <div class="form-group">
                    <label>Mobile</label>
                    <input class="form-control" type="text" placeholder="Search with Mobile" id="mobile" name="mobile">

                </div>
            </div>
            <div class="col-lg-3">

                <div class="form-group">
                    <label>Order ID</label>
                    <input class="form-control" type="text" placeholder="Search with Order ID" id="orderId" name="orderId">

                </div>
            </div>


            <div class="col-lg-3">

                <div class="form-group">
                    <button type="submit" class="btn btn-primary" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Search&nbsp;&nbsp;&nbsp;&nbsp;</button>

                </div>
            </div>

        </form>


    </div>



</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> User Search Results </h3>
            </div>


            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Date Time </th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                    if($nothing == 1) {
                        if ($count > 0) {
                            foreach ($result as $res) {
                                //var_dump($res); exit;
                                $res = (array)$res;
                                ?>

                                <tr>
                                    <td><?php echo $res['name'] ?></td>
                                    <td><?php echo $res['email'] ?></td>
                                    <td><?php echo $res['mobile'] ?></td>
                                    <td><?php echo date('d-m-Y h:i:s', strtotime($res['dateAdded'])) ?>
                                    <td> <?php if ($res['status'] == 0) {
                                            echo "Initialized";
                                        } elseif ($res['status'] == 1) {
                                            echo "Success";
                                        } elseif ($res['status'] == 2) {
                                            echo "Failed";
                                        } ?>  </td>

                                </tr>
                                <?php
                                if ($res['status'] == "2") {
                                    ?>
                                    <tr style="background-color: #ffc">
                                        <td>Gateway Response</td>
                                        <td colspan="6"> <?php echo $res['response'] ?></td>
                                    </tr>
                                    <?php
                                }
                                if ($res['status'] == "1") {
                                    ?>

                                    <tr style="background-color: greenyellow">
                                        <td>Transaction ID</td>
                                        <td colspan="2"> <?php echo $res['txnId'] ?> </td>
                                        <td> Amount</td>
                                        <td colspan="2"><?php echo $res['paytmAmount'] ?>  </td>
                                    </tr>

                                    <?php
                                }
                                ?>


                                <?php
                            }
                        } else {
                            ?>

                            <tr class="active">
                                <td colspan="5">Nothing Found</td>

                            </tr>

                            <?php
                        }
                    } else {
                        ?>
                        <tr class="active" style="background-color: #faf2cc">
                            <td colspan="5">Plesse enter ID Email or Search</td>

                        </tr>

                    <?php
                    }

                    ?>


                    </tbody>
                </table>



            </div>
        </div>
    </div>
    <!-- /.row -->

