<?php

    if(!is_object($user)){
        $user = (object)$user;
    }

echo "<pre>";
print_r($user);
echo "</pre>";
    ?>

<script>
  <?php
      if($user->proStatus==0){
        ?>
  $(document).ready(function(){
   // $(".info").hide();
  });
  <?php
      }
  ?>
</script>



<div id="content">
  <div id="title">
    <h1 class="inner job_page title-2"><?php echo ($user->Name == "")? "No Name" : ucwords($user->Name)?> <span id="jobs-counter"> - <?php echo ($user->Res_Headline!="")?$user->Res_Headline:""?> </span>
      <ul class="breadcrumb-inner">
        <li> <a href="index.html">Home</a></li>
        <li><a href="candidate.html">Candidate</a></li>
      </ul>
    </h1>
  </div>
  <div class="inner"> 
    
    <!-- Content Inner -->
    <div class="content-inner candidate-single"> 
      
      <!-- Content Left -->
      



      <div class="content-left info">
        <div class="block background job_block">
          <div id="map-container" class="candidate-pic"> <img src="images/candidate.png"  alt="Candidate picture"/> </div>
          <h2 class="title-3">Contact Details</h2>
          <div class="block-content">
            <table  border="1" class="list_info">
              <tr>
                <td>Name</td>
                <td><?php echo ($user->Name == "")? "Update Name":ucwords($user->Name)?></td>
              </tr>
              <tr>
                <td>Age</td>
                <td><?php
                 // print_r($user);
                 $dob = $user->Dob;
                  //echo $dob; exit;
                //$diff = intval(substr(date('Ymd') - date('Ymd', strtotime($dob)), 0, -4));
                  $today = date('Y-m-d');
                  $dob1 = date('Y-m-d', strtotime($dob));
                  //var_dump($dob1);
                  $diff = abs(strtotime($today) - strtotime($dob));
                  $years = floor($diff / (365*60*60*24));
                  echo $years;
                ?> Years Old</td>
              </tr>
              <tr>
                <td>Location</td>
                <td>Delhi</td>
              </tr>
              <tr>
                <td>Experiance</td>
                <td><?php echo isset($user->Yr_Of_Exp)?$user->Yr_Of_Exp:0 ?> Years <?php echo isset($user->Mth_Of_Exp)?$user->Mth_Of_Exp:0 ?> Months </td>
              </tr>
             <!-- <tr>
                <td>Education</td>
                <td><?php echo isset($user->Edu_Desc)?$user->Edu_Desc:"" ?>, <?php echo isset($user->Edu_Other)?$user->Edu_Other:"" ?> </td>
              </tr> -->
              <tr>
                <td>Career Level</td>
                <td><?php 
                if($user->Yr_Of_Exp >=0 && $user->Yr_Of_Exp <=4 ){
                    echo "Beginnner Level";
                }
                else if($user->Yr_Of_Exp >=5 && $user->Yr_Of_Exp <=10 ){
                    echo "Middile Level";
                }
                else if($user->Yr_Of_Exp  >10 ){
                    echo "Senior Level";
                }
                ?></td>
              </tr>
              <tr>
                <td>Phone</td>
                <td><?php echo ($user->Mobile == "")? ucwords($user->Mobile):"Update Mobile"?></td>
              </tr>
              <tr>
                <td>E-mail</td>
                <td><?php echo $user->Email?></td>
              </tr>
              
            </table>
          </div>
        </div>
      </div>
      <!-- /Content Left --> 
      
      <!-- Content Center -->
      <div class="content-center info">

      <!--  <div class="heading-l">
          <h2> Profile Description </h2>
        </div>
        <div class="row-fluid">
          <div class="page-nav">
            <div class="span3 pull-left" style="margin-bottom:25px;">
              <button class="btn gray jobbtn">back to listing</button>
            </div>
            <div class="span2 pull-right">
              <button class="btn gray next-btn" style="margin-left:10px;">Next</button>
            </div>
            <div class="span2 pull-right">
              <button class="btn gray pre-btn">Previous</button>
            </div>
          </div>
        </div>  -->

        <div class=" content-center border box-1 single-candidate">
          <div id="job-content-field">
            <div class="field-container single no_border">
              <div class="header-fields">
                <div class="title-company">
                  <div class="title"><a href="#"><?php echo (trim($user->Name) == "" || trim($user->Name)==null )? "Name not available":ucwords($user->Name)?></a></div>
                  <div class="company"><?php 
                   $dob= $user->Dob;
                $diff = intval(substr(date('Ymd') - date('Ymd', strtotime($dob)), 0, -4));
                echo $diff;
                  ?> Years Old - <?php echo ($user->City_Desc != "")? ucwords($user->City_Desc):""?>, <?php echo ($user->St_Desc != "")? ucwords($user->St_Desc):""?> , <?php echo ($user->Cnt_Desc != "")? ucwords($user->Cnt_Desc):""?></div>
                </div>
              </div>
              <div class="body-field">
                <div class="teaser">
                  <p> <?php echo ($user->Res_Headline != "")? ucwords($user->Res_Headline):""?></p>
                </div>
               <!-- <div class="full-body" style="display: block">
                  <p>Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                </div> -->
              </div>
              <div class="block-fields">
                <div class="block skills">
                  <h4>My Skills</h4>
                  <div class="block-content">
                    <div class = "field roll-with-description show">
                      <div class = "roll-button"><span></span></div>
                      <div class = "roll-field">
                        <div class = "label">5 Years of Experience</div>
                        <div class = "progressbar"><span class = "progress-count" data-level = "60"></span></div>
                        <div class = "description">...</div>
                      </div>
                    </div>
                    <div class = "field roll-with-description show">
                      <div class = "roll-button"><span></span></div>
                      <div class = "roll-field">
                        <div class = "label">Perfect Written &amp; Spoken English</div>
                        <div class = "progressbar"><span class = "progress-count" data-level = "100"></span></div>
                        <div class = "description">...</div>
                      </div>
                    </div>
                    <div class = "field roll-with-description show">
                      <div class = "roll-button"><span></span></div>
                      <div class = "roll-field">
                        <div class = "label">3 Foreign Languages</div>
                        <div class = "progressbar"><span class = "progress-count" data-level = "65"></span></div>
                        <div class = "description">Preferred languages are Arabic, French &amp; Italian. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.</div>
                      </div>
                    </div>
                    <!-- Cleaner -->
                    <div class="clear"></div>
                    <!-- /Cleaner --> 
                  </div>
                </div>
                <div class="block">
                  <h4>Additional Skills</h4>
                  <div class="block-content">
                    <div class = "tag-field">Work Permit</div>
                    <div class = "tag-field">5 Years Experience</div>
                    <div class = "tag-field">MBA</div>
                    <div class = "tag-field">Magento Certified</div>
                    <div class = "tag-field">Perfect Written &amp; Spoken English</div>
                  </div>
                  <!-- Cleaner -->
                  <div class="clear"></div>
                  <!-- /Cleaner --> 
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="clear"></div>
        <div class="heading-l">
          <h2> Similar Candidates </h2>
        </div>
        <div class="block border recruiter box-1 candidates-box mr0">
          <div class="block-content">
            <div class="recruiter_photo"><img src="images/recruiter.jpg"  alt="user"/></div>
            <div class="recruiter_info">
              <div class="row-field">
                <div class="span5 pull-left first">
                  <div class="title">Abu Antar</div>
                  <div class="location">24 Years Old - Sydney, AU</div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Lorem ipsum dolor sit amet, consectetur adipisicing elit. <a>Read More</a></p>
                </div>
              </div>
            </div>
            <ul class="candidate-meta">
              <li class="pull-left">Experience: <span>5 Years</span></li>
              <li class="pull-center">Degree: <span>MBA</span></li>
              <li class="pull-right">Career Level: <span>Mid Career</span></li>
            </ul>
          </div>
        </div>
        <div class="clear"></div>
        <!-- Clear Line --> 
        
      </div>
      <!-- /Content Center -->
      <div class="clear"></div>
      <!-- Clear Line --> 
      
    </div>
    <!-- /Content Inner --> 
    
  </div>
</div>
