
	<div class="row">
		<h3 class="bottom-margin-5">Our Services</h3><br><br>

		<div class="col-sm-4 scrollimation fade-up in">

			<div class="media">
				<div class="media-body">
					<h4><strong>Job Search Assistant</strong></h4>
					<p>Job Search Assistant where we go extra mile for candidates) service works as your personal Relationship Manager providing </p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"1"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

		<div class="col-sm-4 scrollimation fade-up d1 in">

			<div class="media">
				<div class="media-body">
					<h4><strong>Profile Highlighter</strong></h4>
					<p>Get more visibility in a recruiter search and stand a better chance of catching their attention amongst millions of candidate profiles on Jobsspeed.com with this premium service.</p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"2"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

		<div class="col-sm-4 scrollimation fade-up d2 in">

			<div class="media">
				<div class="media-body">
					<h4><strong>Resume Blast</strong></h4>
					<p>Resume Blast India or Gulf is a resume distribution service that helps you get noticed by job consultants and recruiters, registered on Jobsspeed.com. Your Resume gets published across the India + Gulf.  </p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"3"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

	</div>

	<hr style="margin:20px 0;">

	<div style="margin:50px 0;" class="row">

		<div class="col-sm-4 scrollimation fade-up in">

			<div class="media">
				<div class="media-body">
					<h4><strong>Resume Writing India</strong></h4>
					<p>An experienced professional resume writer will develop your resume that will highlight your achievements, strengths, elaborate work experiences, key responsibilities.</p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"4"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

		<div class="col-sm-4 scrollimation fade-up d1 in">

			<div class="media">
				<div class="media-body">
					<h4><strong>Resume Writing International</strong></h4>
					<p>An experienced professional resume writer will develop your resume that will highlight your achievements, strengths, elaborate work experiences, key responsibilities.</p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"5"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

		<div class="col-sm-4 scrollimation fade-up d2 in">

			<div class="media">
				<div class="media-body">
					<h4><strong>Social Profile Writing</strong></h4>
					<p>Social Profiler Writing is a personalized social profile writing that gets you noticed by the people who matter and help you take the next step in your career.</p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"6"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

	</div>

	<hr style="margin:20px 0;">

	<div class="row">

		<div class="col-sm-4 scrollimation fade-up in">

			<div class="media">
				<div class="media-body">
					<h4><strong>Visual Resume</strong></h4>
					<p>Attract more recruiters with your Resume by improving the way it represents you. Visual Resume Premium will deliver:
					</p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"7"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

		<div class="col-sm-4 scrollimation fade-up d1 in">

			<div class="media">
				<div class="media-body">
					<h4><strong>We Guarantee You a Job</strong></h4>
					<p>Our service provides Job Search Guidance for Job Aspirants backed by a GAURANTEE (or 50% Refund) to find you a JOB within 6 months.</p>
					<p style="float:right; margin:15px 30px 15px 0; border:1px solid #ccc; padding:5px;"><a href="<?php echo $this->url('rservices',array("action"=>"service","id"=>"8"))?>"><strong>Read more..</strong></a></p>
				</div>
			</div>

		</div>

	</div>
