<!DOCTYPE html>
<html class="no-js">
<head>
<title>Big</title>
<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lato:300,400,700&amp;subset=latin,latin-ext"/>
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700' rel='stylesheet' type='text/css'>
<link href="<?php echo $this->basepath('css/font-awesome.css')?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basepath('css/font-awesome-ie7.css')?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basepath('css/bootstrap.css')?>" rel="stylesheet">
<link href="<?php echo $this->basepath('css/bootstrap-responsive.css')?>" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('css/reset.css')?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('css/style.css')?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('css/jquery.combosex.css')?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('css/jquery.flexslider.css')?>" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('css/jquery.scrollbar.css')?>" />

<!--[if (lte IE 9)]>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->basepath('css/iefix.css')?>" />
    <![endif]-->
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.1.7.2.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery-ui.1.7.2.min.js')?>"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.combosex.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.flexslider-min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.mousewheel.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.easytabs.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.gmap.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.scrollbar.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jQuery.menutron.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/jquery.isotope.min.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->basepath('js/custom.js')?>"></script>

</head>
<body>

<!-- Bar -->
<div id="bar">
  <div class="inner"> 
    
    <!-- User Menu -->
    <ul id="user-menu">
      <li id="login" class="first"><a href="#">Login</a></li>
      <li id="register"><a href="#">Register</a></li>
    </ul>
    <!-- /User Menu --> 
    
  </div>
</div>
<!-- /Bar --> 

<!-- Header -->
<div id="header">
  <div class="inner"> 
    
    <!-- Logo -->
    <div id="logo"> <a href="index.html"><img src="<?php echo $this->basepath('images/Logo.png')?>" width="205" height="50"  alt="logo"/></a><a class="menu-hider"></a></div>
    <!-- /Logo -->
    
    <ul id="navigation">
      <li class="current"> <a href="index.html">Home</a></li>
      <li class="first expanded"><a href="jobs.html">Jobs</a>
        <ul class="submenu">
          <li><a href="jobs.html">Job listing</a></li>
          <li><a href="job.html">Job Details</a></li>
        </ul>
      </li>
      <li class="first expanded"><a href="candidates-listing.html">Candidates</a>
        <ul class="submenu">
          <li><a href="candidates-listing.html">Candidate Listing (with sidebar)</a></li>
          <li><a href="candidates-listing-no-sidebar.html">Candidate listing (without)</a></li>
<li><a href="candidate.html">Candidate</a></li>
        </ul>
      </li>
      <li><a href="partners.html">Partners</a></li>
      <li><a href="about-us.html">About Us</a></li>
      <li><a href="contacts.html">Contact</a></li>
    </ul>
  </div>
</div>
<!-- /Header --> 

<!-- Search -->
<div id="search">
  <div class="inner">
    <form id="search-form" action="http://uouapps.com/careers/index.html" class="search-bar-home">
      <label class="in in2">Search Job</label>
      <input type="text" placeholder="job title, keywords or company name" class="textfield-with-callback"/>
      <input type="text" placeholder="city, province, or region" class="textfield-with-callback"/>
      <input type="submit" value="Search" id="search-submit" class="pull-right"/>
    </form>
    <div id="more-options"></div>
    <div class="clear"></div>
    <!-- Clear Line -->
    
    <div id="options"></div>
  </div>
</div>
<!-- /Search --> 

<!-- Content -->
<div id="content"> 
  
  <!-- Banner Area -->
  <section class="header-banner" style="background:url(images/home-bg.jpg) repeat-x; height:300px;"> 
    </section>
  <!-- /Banner Area -->  
  <div class="clear"></div>


  <?php echo $this->content; ?>


</div>
<!-- /Content --> 

<!-- Footer -->
<div id="footer">
  <section class="row-fluid">
    <div id="stories" class="block border">
      <div class="inner">
        <section class="row-fluid">
          <section class="span12 storyblock">
            <h2>Success Stories</h2>
            <div class="block-content butt-flexslider">
              <ul class="slides">
                <li class="user-avatar"> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-1.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-4.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-5.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> </li>
                <li class="user-avatar"> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-5.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-4.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-1.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> </li>
                <li class="user-avatar"> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-5.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-4.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-1.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> </li>
                <li class="user-avatar"> <a href="#"> <img src="<?php echo $this->basepath('content/users-avatar/user-1.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-4.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-5.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-2.jpg')?>" alt="User" height="114" width="113"/>
                  <div class="effect"></div>
                  </a> <a href="#"><img src="<?php echo $this->basepath('content/users-avatar/user-3.jpg')?>" alt="User" height="114" width="114"/>
                  <div class="effect"></div>
                  </a> </li>
              </ul>
              <div class="story_block">
                <div class="before"></div>
                <div class="title">Jane’s Success Story</div>
                <div class="text"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi.
                  Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.
                  Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus. </div>
                <div class="link">Jane Smithson</div>
                <div class="info"> Company Name: UOU Apps<br/>
                  Job Role: Technology/IT<br/>
                  Date Posted: 17 June 2013 </div>
              </div>
            </div>
          </section>
        </section>
      </div>
    </div>
    <section class="footer-wrapper">
      <section class="row-fluid">
        <section class="inner">
          <div id="site-description">
            <h3><img src="<?php echo $this->basepath('images/Logo.png')?>" width="205" height="50"  alt=""/></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Praesent sodales velit quis augue. Cras suscipit.</p>
          </div>
          <div id="footer-menu">
            <div id="nav-menu" class="footer-menu">
              <h2>Navigation</h2>
              <div class="left">
                <ul>
                  <li><a href="index.html">Home</a></li>
                  <li><a href="job-listing-1.html">Jobs</a></li>
                  <li><a href="partners.html">Partners</a></li>
                  <li><a href="about-us.html">About Us</a></li>
                </ul>
              </div>
              <div class="right">
                <ul>
                  <li><a href="contacts.html">Contact Us</a></li>
                  <li><a href="terms-and-conditions.html">Terms &amp; Conditions</a></li>
                  <li><a href="privacy-policy.html">Privacy Policy</a></li>
                </ul>
              </div>
            </div>
            <div id="fol-menu" class="footer-menu">
              <h2>Follow Us</h2>
              <ul>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Youtube</a></li>
              </ul>
            </div>
            <div id="job-menu" class="footer-menu">
              <h2>Popular Jobs</h2>
              <ul>
                <li><a href="#">Web Developer</a></li>
                <li><a href="#">Web Designer</a></li>
                <li><a href="#">UX Engineer</a></li>
                <li><a href="#">Account Manager</a></li>
              </ul>
            </div>
          </div>
        </section>
      </section>
    </section>
  </section>
</div>
<!-- /Footer -->
<div class="clearfix"></div>
<!-- Copyright -->

<div id="copyright">
  <div class="inner">
    <div class="row-fluid">
      <!-- Copyright Text -->
      <div id="copyright-text">Copyright 2016  | All Rights Reserved </div>
      <!-- /Copyright Text -->
      <!-- Copyright Social Link -->
      <div id="copyright-link">
        <div class="buttons">
          <ul class="top_soical_icons pull-right	">
            <li> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
            <li> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
            <li> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
            <li> <a href="#"> <i class="fa fa-linkedin-square"></i> </a> </li>
            <li> <a href="#"> <i class="fa fa-pinterest"></i> </a> </li>
            <li> <a href="#"> <i class="fa fa-dribbble"></i> </a> </li>
          </ul>
        </div>
      </div>
      <!-- /Copyright Social Link -->

      <a class="scrollTop" href="#header" style="display: none;">
        <div id = "up_container"> <span></span> </div>
      </a> </div>
  </div>
</div>

<!-- /Copyright -->

</body>
</html>
