<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Dashboard <small>Statistics </small>
        </h1>
        <ol class="breadcrumb">
            <li class="active">
                <i class="fa fa-dashboard"></i> Payment Status
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->



<div class="row">
    <div class="col-lg-12 col-md-6">

            <form role="form" method="post" id="confirmPaymentForm" action="<?php echo  $this->url("sales",array("controller"=>"index","action"=>"confirm")) ?>">

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Email</label>
                        <input class="form-control" type="text" placeholder="Search with Email" name="email">
                    </div>
                </div>

                <div class="col-lg-3">

                    <div class="form-group">
                        <label>Mobile</label>
                        <input class="form-control" type="text" placeholder="Search with Mobile" id="mobile">

                    </div>
                </div>


                <div class="col-lg-3">

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" style="margin-top:25px; margin-left: 25px; width:18em ;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Search&nbsp;&nbsp;&nbsp;&nbsp;</button>

                    </div>
                </div>

            </form>


    </div>



</div>
<!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> User Search Results </h3>
            </div>


                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Mobile</th>
                            <th>Date Time </th>
                            <th>Status</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php
                       // if($result->count() > 0) {
                            foreach ($result as $res) {
                                var_dump($res); exit;
                                ?>

                                <tr class="active">
                                    <td>Atul Walkar</td>
                                    <td>shrawan.walkar@gmail.com</td>
                                    <td>99225515752 9595674545</td>
                                    <td>29/07/2016 <br>30/07/2016</td>
                                    <td>Active</td>
                                </tr>


                                <?php
                            }
                       // } else
                        {
                            ?>

                            <tr class="active">
                                <td colspan="5">Nothing Found</td>

                            </tr>

                            <?php
                        }

                        ?>


                        </tbody>
                    </table>



        </div>
    </div>
</div>
<!-- /.row -->

