<div id="search">
    <div class="inner">
        <form id="search-form" action="#" class="search-bar-home">
            <label class="in in2">Search Job</label>
            <input type="text" placeholder="job title, keywords or company name" class="searchjob"/>
            <input type="text" placeholder="city, province, or region" class="searchjob"/>
            <input type="submit" value="Search" id="search-submit" class="pull-right"/>
        </form>
        <div id="more-options"></div>
        <div class="clear"></div>
        <!-- Clear Line -->

        <div id="options"></div>
    </div>
</div>

<div id="content">

    <!-- Banner Area -->
    <section class="header-banner" style="background:url(images/home-bg.jpg) repeat-x; height:300px;">
    </section>
    <!-- /Banner Area -->
    <div class="clear"></div>

    <div class="inner">
        <!-- Content Inner -->
        <div class="content-inner">

            <!-- Content Center -->
            <div class="content-center frontpage">
                <div class="heading-l">
                    <h2> Find A Job Per </h2>
                </div>
                <div id="explore" class="non-title-border">
                    <div class="block-content">
                        <ul class="tabs">
                            <li><a href="#industry">By Industry</a></li>
                            <li><a href="#type">By Role</a></li>
                            <li class="last"><a href="#country"> By Country</a></li>
                        </ul>
                        <div id="industry"  class="box-1">
                            <div class="scroll-container">
                                
                                <?php 
                                $count = $industry->count();
                                $leftcount = $count/2;
                                $class = "left";
                                $leftArray = array();
                                $rightArray = array();
                                $x = 0;
                                foreach ($industry as $ind ){
                                   // var_dump($ind); exit;
                                    if($leftcount <=$x ){
                                        $leftArray[] = $ind;
                                        
                                    } else {
                                      $rightArray[] = $ind;
        
                                    }
                                    $x++;
                                }
                                //var_dump(count($leftArray));
                                //var_dump(count($rightArray));
                                
                                ?>
                                
                                <div class="left">
                                    
                                    <ul>
                                        <?php 
                                            foreach($leftArray as $i){
                                                
                                        ?>
                                        <!--<li><a href="#">Support Services<span>(34)</span></a></li> -->
                                        <li><a href="#"><?php echo $i->Ind_Desc;?><span>(34)</span></a></li>
                                         <?php 
                                        }
                                        ?>
                                        
                                    </ul>
                                  
                                </div>
                                
                                 <div class="left">
                                    
                                    <ul>
                                        <?php 
                                            foreach($rightArray as $i){
                                                
                                        ?>
                                        <!--<li><a href="#">Support Services<span>(34)</span></a></li> -->
                                        <li><a href="#"><?php echo $i->Ind_Desc;?><span>(34)</span></a></li>
                                         <?php 
                                        }
                                        ?>
                                        
                                    </ul>
                                  
                                </div>
                               
                                
                                <div class="clear"></div>
                            </div>
                            <div class="external-scroll_y">
                                <div class="scroll-element_outer">
                                    <div class="scroll-element_size"></div>
                                    <div class="scroll-element_inner"></div>
                                    <div class="scroll-bar"></div>
                                </div>
                            </div>
                        </div>
                        <div id="type"  class="box-1">
                            <div class="scroll-container">
                                <div class="info">
                                    <p>Find the Jobs By roles </p>
                                </div>
                                <?php 
                                $count = $jobrole->count();
                                $roleLeftcount = $count/2;
                                $class = "left";
                                $roleLeftArray = array();
                                $roleRightArray = array();
                                $x = 0;
                                foreach ($jobrole as $job ){
                                    //var_dump($job); exit;
                                    if($roleLeftcount <=$x ){
                                        $roleLeftArray[] = $job;
                                        
                                    } else {
                                      $roleRightArray[] = $job;
        
                                    }
                                    $x++;
                                }
                                //var_dump(count($leftArray));
                                //var_dump(count($rightArray));
                                
                                ?>
                                
                                <div class="left">
                                    <ul>
                                        <?php 
                                            foreach($roleLeftArray as $i){
                                                
                                        ?>
                                        <!--<li><a href="#">Support Services<span>(34)</span></a></li> -->
                                        <li><a href="#"><?php echo $i->Jobr_Desc;?><span>(34)</span></a></li>
                                         <?php 
                                        }
                                        ?>
                                    </ul>
                                </div>
                                <div class="right">
                                    <ul>
                                         <?php 
                                            foreach($roleRightArray as $i){
                                                if(strpos($i->Jobr_Desc, "---") === FALSE){
                                                
                                        ?>
                                        <!--<li><a href="#">Support Services<span>(34)</span></a></li> -->
                                        <li><a href="#"><?php echo $i->Jobr_Desc;?><span>(34)</span></a></li>
                                         <?php 
                                                }
                                        }
                                        ?>
                                    </ul>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="external-scroll_y">
                                <div class="scroll-element_outer">
                                    <div class="scroll-element_size"></div>
                                    <div class="scroll-element_inner"></div>
                                    <div class="scroll-bar"></div>
                                </div>
                            </div>
                        </div>
                        <div id="country"  class="box-1">
                            <div class="scroll-container">
                                <div class="left">
                                    <ul>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Afghanistan.png')?>" alt="Flag" height="24" width="24"/>Afghanistan<span>(7)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/African%20Union.png')?>" alt="Flag" height="24" width="24"/>African Union<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Aland.png')?>" alt="Flag" height="24" width="24"/>Aland<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Albania.png')?>" alt="Flag" height="24" width="24"/>Albania<span>(7)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Alderney.png')?>" alt="Flag" height="24" width="24"/>Alderney<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Algeria.png')?>" alt="Flag" height="24" width="24"/>Algeria<span>(4)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/American%20Samoa.png')?>" alt="Flag" height="24" width="24"/>American Samoa<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Andorra.png')?>" height="24" alt="Flag" width="24"/>Andorra<span>(5)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Angola.png')?>" alt="Flag" height="24" width="24"/>Angola<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Anguilla.png')?>" alt="Flag" height="24" width="24"/>Anguilla<span>(8)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Antarctica.png')?>" alt="Flag" height="24" width="24"/>Antarctica<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Antigua%20Barbuda.png')?>" alt="Flag" height="24" width="24"/>Antigua &amp; Barbuda<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Arab%20League.png')?>" alt="Flag" height="24" width="24"/>Arab League<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Argentina.png')?>" alt="Flag" height="24" width="24"/>Argentina<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Armenia.png')?>" alt="Flag" height="24" width="24"/>Armenia<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Aruba.png')?>" alt="Flag" height="24" width="24"/>Aruba<span>(8)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/ASEAN.png')?>" alt="Flag" height="24" width="24"/>ASEAN<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Afghanistan.png')?>" alt="Flag" height="24" width="24"/>Afghanistan<span>(7)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/African%20Union.png')?>" alt="Flag" height="24" width="24"/>African Union<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Aland.png')?>" alt="Flag" height="24" width="24"/>Aland<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Albania.png')?>" alt="Flag" height="24" width="24"/>Albania<span>(7)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Alderney.png')?>" alt="Flag" height="24" width="24"/>Alderney<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Algeria.png')?>" alt="Flag" height="24" width="24"/>Algeria<span>(4)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/American%20Samoa.png')?>" alt="Flag" height="24" width="24"/>American Samoa<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Andorra.png')?>" alt="Flag" height="24" width="24"/>Andorra<span>(5)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Angola.png')?>" alt="Flag" height="24" width="24"/>Angola<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Anguilla.png')?>" alt="Flag" height="24" width="24"/>Anguilla<span>(8)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Antarctica.png')?>" alt="Flag" height="24" width="24"/>Antarctica<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Antigua%20Barbuda.png')?>" alt="Flag" height="24" width="24"/>Antigua &amp; Barbuda<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Arab%20League.png')?>" alt="Flag" height="24" width="24"/>Arab League<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Argentina.png')?>" alt="Flag" height="24" width="24"/>Argentina<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Armenia.png')?>" alt="Flag" height="24" width="24"/>Armenia<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Aruba.png')?>" alt="Flag" height="24" width="24"/>Aruba<span>(8)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/ASEAN.png')?>" alt="Flag" height="24" width="24"/>ASEAN<span>(3)</span></a></li>
                                    </ul>
                                </div>
                                <div class="right">
                                    <ul>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kenya.png')?>" alt="Flag" height="24" width="24"/>Kenya<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kiribati.png')?>" alt="Flag" height="24" width="24"/>Kiribati<span>(4)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kosovo.png')?>" alt="Flag" height="24" width="24"/>Kosovo<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kuwait.png')?>" alt="Flag" height="24" width="24"/>Kuwait<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kyrgyzstan.png')?>" alt="Flag" height="24" width="24"/>Kyrgyzstan<span>(1)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Laos.png')?>" alt="Flag" height="24" width="24"/>Laos<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Latvia.png')?>" alt="Flag" height="24" width="24"/>Latvia<span>(4)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Lebanon.png')?>" alt="Flag" height="24" width="24"/>Lebanon<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Lesotho.png')?>" alt="Flag" height="24" width="24"/>Lesotho<span>(5)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Liberia.png')?>" alt="Flag" height="24" width="24"/>Liberia<span>(7)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Libya.png')?>" alt="Flag" height="24" width="24"/>Libya<span>(1)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Liechtenstein.png')?>" alt="Flag" height="24" width="24"/>Liechtenstein<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Lithuania.png')?>" alt="Flag" height="24" width="24"/>Lithuania<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Luxembourg.png')?>" alt="Flag" height="24" width="24"/>Luxembourg<span>(8)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Macao.png')?>" alt="Flag" height="24" width="24"/>Macao<span>(5)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Macedonia.png')?>" alt="Flag" height="24" width="24"/>Macedonia<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Madagascar.png')?>" alt="Flag" height="24" width="24"/>Madagascar<span>(1)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kenya.png')?>" alt="Flag" height="24" width="24"/>Kenya<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kiribati.png')?>" alt="Flag" height="24" width="24"/>Kiribati<span>(4)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kosovo.png')?>" alt="Flag" height="24" width="24"/>Kosovo<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kuwait.png')?>" alt="Flag" height="24" width="24"/>Kuwait<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Kyrgyzstan.png')?>" alt="Flag" height="24" width="24"/>Kyrgyzstan<span>(1)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Laos.png')?>" alt="Flag" height="24" width="24"/>Laos<span>(3)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Latvia.png')?>" alt="Flag" height="24" width="24"/>Latvia<span>(4)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Lebanon.png')?>" alt="Flag" height="24" width="24"/>Lebanon<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Lesotho.png')?>" alt="Flag" height="24" width="24"/>Lesotho<span>(5)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Liberia.png')?>" alt="Flag" height="24" width="24"/>Liberia<span>(7)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Libya.png')?>" alt="Flag" height="24" width="24"/>Libya<span>(1)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Liechtenstein.png')?>" alt="Flag" height="24" width="24"/>Liechtenstein<span>(6)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Lithuania.png')?>" alt="Flag" height="24" width="24"/>Lithuania<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Luxembourg.png')?>" alt="Flag" height="24" width="24"/>Luxembourg<span>(8)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Macao.png')?>" alt="Flag" height="24" width="24"/>Macao<span>(5)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Macedonia.png')?>" alt="Flag" height="24" width="24"/>Macedonia<span>(2)</span></a></li>
                                        <li><a href="#"><img src="<?php echo $this->basePath('content/flag-icons/Madagascar.png')?>" alt="Flag" height="24" width="24"/>Madagascar<span>(1)</span></a></li>
                                    </ul>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="external-scroll_y">
                                <div class="scroll-element_outer">
                                    <div class="scroll-element_size"></div>
                                    <div class="scroll-element_inner"></div>
                                    <div class="scroll-bar"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="clear"></div>
                <!--Latest Jobs Block-->
                <div id="latest-job">
                    <div class="heading-l">
                        <h2> Latest Jobs </h2>
                    </div>
                    <div class="latest-job-wrapper">
                        <div class="block-content dott-flexslider box-1">
                            <ul class="slides">
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                                <li>
                                    <div class="company-logo"><a href="#"><img src="<?php echo $this->basePath('images/job-thumb.jpg')?>"  alt=""/></a>
                                        <div class="nav-buttons">
                                            <ul>
                                                <li class="search"><a><i class="fa fa-search"></i></a></li>
                                                <li class="link"><a href="job.html"><i class="fa fa-link"></i></a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="company-text">
                                        <div class="title"><a href="#">Front-End Developer at Envato</a>
                                            <div class="location">Sydney, Australia</div>
                                        </div>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. <a>Read More</a></div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!--/Latest Jobs Block-->
                <div class="clear"></div>
                <!--Partners Block-->
                <div id="partners">
                    <div class="heading-l">
                        <h2> Our Partners </h2>
                    </div>
                    <div class="block-content box-1">
                        <section class="row-fluid">
                            <ul class="partner-list span4">
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                            </ul>
                            <ul class="partner-list span4">
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                            </ul>
                            <ul class="partner-list span4">
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                                <li><a href="#"><img src="<?php echo $this->basePath('images/client-logo.png')?>"  alt=""/></a></li>
                            </ul>
                        </section>
                    </div>
                </div>
                <!--Partners Block-->
                <div class="clear"></div>
                <!--Price Table Block-->

                <!--
                <div class="heading-l">
                    <h2> Our Prices </h2>
                </div>
                <div class="block-content ">
                    <section class="row-fluid">
                        <ul class="price-list span4 box-1">
                            <li class="pgk-title title-1">Bronze</li>
                            <li class="pgk-price title-2">$ 15</li>
                            <li>1 Job Ad</li>
                            <li>30 Days</li>
                            <li>Standard Positioning</li>
                            <li>1 Lorem Ipsum</li>
                            <li><a class="btn blue" href="#">Choose</a></li>
                        </ul>
                        <ul class="price-list span4 box-1">
                            <li class="pgk-title title-1">Silver</li>
                            <li class="pgk-price title-2">$ 49</li>
                            <li>5 Job Ad</li>
                            <li>45 Days</li>
                            <li>Extandad Positioning</li>
                            <li>5 Lorem Ipsum</li>
                            <li><a class="btn blue" href="#">Choose</a></li>
                        </ul>
                        <ul class="price-list span4 box-1">
                            <li class="pgk-title title-1">Gold</li>
                            <li class="pgk-price title-2">$ 99</li>
                            <li>10 Job Ad</li>
                            <li>60 Days</li>
                            <li>Extra Positioning</li>
                            <li>10 Lorem Ipsum</li>
                            <li><a class="btn blue" href="#">Choose</a></li>
                        </ul>
                    </section>
                </div>
-->
                <!--Price Table Block-->

            </div>
            <!-- /Content Center -->

            <!-- Content Right -->
            <div class="content-right">
                <div id="search-filter" class="block background">
                    <h2 class="title-1">Search</h2>
                    <div class="block-content">
                        <form id="search-job-page" action="http://uouapps.com/careers/post">
                            <label>I am looking for a</label>
                            <select id="search-select" class="select combosexed" style="display: none;">
                                <option selected="selected" value="Job">Job</option>
                                <option value="Something Else 1">Something Else 1</option>
                                <option value="Something Else 2">Something Else 2</option>
                                <option value="Something Else 3">Something Else 3</option>
                            </select><span class="combosex_main select combosex_with_append combosex_select"><span class="combosex_arrow combosex_arrow_down" style="width: 20px;"><em></em></span><span class="combosex_input_span"><a href="javascript:void(0)" class="combosex_display">Job</a></span><input type="hidden" class="combosex_def" value="Job"><input type="hidden" class="combosex_value" value="Job"><span class="combosex_spinner"></span></span>
                            <label>in</label>
                            <input type="text" placeholder="Location" class="textfield-with-callback combosexed" style="display: none;"><span class="combosex_main textfield combosex_with_append combosex_text"><span class="combosex_input_span"><span class="combosex_ph" style="display: inline;">Location</span><input autocomplete="off" type="text" class="combosex_input combosex_input_4" value=""><a rel="4" class="combosex_append">+</a></span><input type="hidden" class="combosex_def" value=""><input type="hidden" class="combosex_value" value=""><span class="combosex_spinner"></span></span>
                            <input type="text" placeholder="Industry / Role" class="textfield-with-callback combosexed" style="display: none;"><span class="combosex_main textfield combosex_with_append combosex_text"><span class="combosex_input_span"><span class="combosex_ph" style="display: inline;">Industry / Role</span><input autocomplete="off" type="text" class="combosex_input combosex_input_5" value=""><a rel="5" class="combosex_append">+</a></span><input type="hidden" class="combosex_def" value=""><input type="hidden" class="combosex_value" value=""><span class="combosex_spinner"></span></span>
                            <input type="submit" value="Search" id="search-job-page-submit">
                        </form>
                    </div>
                    <h2 class="title-1">Results Filtering</h2>
                    <div class="block-content">
                        <div class="filter-category">
                            <h3>By Region</h3>
                            <div class="filter-content show">
                                <div class="filter-container" style="display: block;">
                                    <div class="major">
                                        <ul>
                                            <li class="expanded"> <a class="noactive">Asia<span>(3218)</span></a>
                                                <ul style="display: none;">
                                                    <li><a href="#">Iraq<span>(834)</span></a></li>
                                                    <li class="expanded"> <a class="noactive">Jordan<span>(15218)</span></a>
                                                        <ul style="display: none;">
                                                            <li><a href="#">Ajloun<span>(834)</span></a></li>
                                                            <li><a href="#">Irbid<span>(15218)</span></a></li>
                                                            <li><a href="#">Jerash<span>(834)</span></a></li>
                                                        </ul>
                                                    </li>
                                                    <li><a href="#">Saudi Arabia<span>(14902)</span></a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Africa<span>(834)</span></a></li>
                                            <li><a href="#">Europe<span>(15218)</span></a></li>
                                            <li><a href="#">North America<span>(14902)</span></a></li>
                                            <li><a href="#">Central America<span>(1347)</span></a></li>
                                        </ul>
                                    </div>
                                    <div class="minor hide">
                                        <ul style="display: none;">
                                            <li><a href="#">South America<span>(5834)</span></a></li>
                                            <li><a href="#">Oceania<span>(6020)</span></a></li>
                                        </ul>
                                        <div class="minor-label">See More</div>
                                    </div>
                                </div>
                                <div class="show-hide-button"><span></span></div>
                            </div>
                        </div>
                        <div class="filter-category">
                            <h3>By Industry</h3>
                            <div class="filter-content show">
                                <div class="filter-container" style="display: block;">
                                    <div class="major">
                                        <ul>
                                            <li><a href="#">Administration<span>(34)</span></a></li>
                                            <li><a href="#">Manufacturing<span>(142)</span></a></li>
                                            <li><a href="#">Healthcare &amp; Science<span>(67)</span></a></li>
                                            <li><a href="#">Media &amp; Creative<span>(24)</span></a></li>
                                            <li><a href="#">Transportation<span>(113)</span></a></li>
                                        </ul>
                                    </div>
                                    <div class="minor hide">
                                        <ul style="display: none;">
                                            <li><a href="#">Administration<span>(34)</span></a></li>
                                            <li><a href="#">Manufacturing<span>(142)</span></a></li>
                                        </ul>
                                        <div class="minor-label">See More</div>
                                    </div>
                                </div>
                                <div class="show-hide-button"><span></span></div>
                            </div>
                        </div>
                        <div class="filter-category">
                            <h3>By Type</h3>
                            <div class="filter-content show">
                                <div class="filter-container" style="display: block;">
                                    <div class="major">
                                        <ul>
                                            <li><a href="#">Banking/Finance Jobs<span>(581)</span></a></li>
                                            <li><a href="#">Administration Jobs<span>(406)</span></a></li>
                                            <li><a href="#">Art/Design/Creative Jobs<span>(176)</span></a></li>
                                            <li><a href="#">Customer Service Jobs<span>(334)</span></a></li>
                                            <li><a href="#">Education/Training Jobs<span>(180)</span></a></li>
                                        </ul>
                                    </div>
                                    <div class="minor hide">
                                        <ul style="display: none;">
                                            <li><a href="#">Banking/Finance Jobs<span>(581)</span></a></li>
                                            <li><a href="#">Administration Jobs<span>(406)</span></a></li>
                                        </ul>
                                        <div class="minor-label">See More</div>
                                    </div>
                                </div>
                                <div class="show-hide-button"><span></span></div>
                            </div>
                        </div>
                        <form id="filter-job-page" action="http://uouapps.com/careers/post">
                            <div class="filter-category">
                                <h3>Type of Contract</h3>
                                <div class="filter-content">
                                    <div class="checkbox-field">
                                        <input id="contact_type_choice_1" type="checkbox" value="1">
                                        <label for="contact_type_choice_1">Full-Time</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="contact_type_choice_2" type="checkbox" value="2">
                                        <label for="contact_type_choice_2">Part-Time</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="contact_type_choice_3" type="checkbox" value="3">
                                        <label for="contact_type_choice_3">Freelance</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="contact_type_choice_4" type="checkbox" value="4">
                                        <label for="contact_type_choice_4">Internship</label>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-category">
                                <h3>Work Experience</h3>
                                <div class="filter-content">
                                    <div class="checkbox-field">
                                        <input id="experience_choice_1" type="checkbox" value="1">
                                        <label for="experience_choice_1">All</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="experience_choice_2" type="checkbox" value="2">
                                        <label for="experience_choice_2">Not Applicable</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="experience_choice_3" type="checkbox" value="3">
                                        <label for="experience_choice_3">Mid-Senior Level</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="experience_choice_4" type="checkbox" value="4">
                                        <label for="experience_choice_4">Entry Level</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="experience_choice_5" type="checkbox" value="5">
                                        <label for="experience_choice_5">Associate</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="experience_choice_6" type="checkbox" value="6">
                                        <label for="experience_choice_6">Director</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="experience_choice_7" type="checkbox" value="7">
                                        <label for="experience_choice_7">Internship</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="experience_choice_8" type="checkbox" value="8">
                                        <label for="experience_choice_8">Executive</label>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-category">
                                <h3>Work Permit</h3>
                                <div class="filter-content">
                                    <div class="checkbox-field">
                                        <input id="permit_choice_1" name="permit" type="radio" value="1">
                                        <label for="permit_choice_1">Full-Time</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="permit_choice_2" name="permit" type="radio" value="2">
                                        <label for="permit_choice_2">Part-Time</label>
                                    </div>
                                    <div class="checkbox-field">
                                        <input id="permit_choice_3" name="permit" type="radio" value="3">
                                        <label for="permit_choice_3">Freelance</label>
                                    </div>
                                </div>
                            </div>
                            <div class="filter-category">
                                <h3>Date Posted</h3>
                                <div class="filter-content">
                                    <div class="dayprogressbar-mover">
                                        <div class="bar ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" aria-disabled="false"><div class="ui-slider-range ui-widget-header ui-corner-all" style="left: 0%; width: 50%;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a><a class="ui-slider-handle ui-state-default ui-corner-all right" href="#" style="left: 50%;"></a></div>
                                        <div class="clear"></div>
                                        <div class="begin"> <span class="count">0</span> <span class="label">Days</span> </div>
                                        <div class="end"> <span class="count">45</span> <span class="label">Days</span> </div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                            </div>
                            <div class="filter-category">
                                <h3>Salary Range</h3>
                                <div class="filter-content">
                                    <div class="rangeprogressbar-mover">
                                        <div class="bar ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" aria-disabled="false"><div class="ui-slider-range ui-widget-header ui-corner-all" style="left: 0.5%; width: 49.5%;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0.5%;"></a><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 50%;"></a></div>
                                        <div class="clear"></div>
                                        <div class="begin">
                                            <input class="count" type="text" count="500" onblur="$(this).removeClass('active')" onfocus="$(this).addClass('active')" value="$500">
                                        </div>
                                        <div class="sepor">to</div>
                                        <div class="end">
                                            <input class="count" type="text" count="62500" onblur="$(this).removeClass('active')" onfocus="$(this).addClass('active')" value="$50 000">
                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                    <div id="saved-search-select">
                                        <select class="select combosexed" style="display: none;">
                                            <option selected="selected" value="No Searches Saved Yet">No Searches Saved Yet</option>
                                        </select><span class="combosex_main select combosex_with_append combosex_select"><span class="combosex_arrow combosex_arrow_down" style="width: 20px;"><em></em></span><span class="combosex_input_span"><a href="javascript:void(0)" class="combosex_display">No Searches Saved Yet</a></span><input type="hidden" class="combosex_def" value="No Searches Saved Yet"><input type="hidden" class="combosex_value" value="No Searches Saved Yet"><span class="combosex_spinner"></span></span>
                                        <a href="#">Save My Search</a> </div>
                                </div>
                            </div>
                            <input type="submit" value="Search" id="filter-job-page-submit">
                        </form>
                    </div>
                </div>
                <!--<div id="advertising" class="block border">
                    <div class="block-content"> <img src="<?php echo $this->basePath('images/sb-ad.jpg')?>" alt="banner ad">
                        <!--<div class="advertising-test">300x250<br/>
                          Ad Banner</div>
                    </div>
                </div>-->
            </div>
            <!-- /Content Right -->

            <div class="clear"></div>
            <!-- Clear Line -->

        </div>
        <!-- /Content Inner -->

    </div>
</div>